FROM golang:1.5

ADD https://get.docker.com/builds/Linux/x86_64/docker-1.10.3 /usr/local/bin/docker

RUN chmod +x /usr/local/bin/docker
RUN curl -sL https://deb.nodesource.com/setup | bash -
RUN apt-get update && apt-get install -y nodejs
RUN npm install -g bower
ENV TAG latest
ENV PATH $PATH:/go/bin:/usr/local/go/bin

COPY . /go/src/github.com/shipyard/shipyard

WORKDIR /go/src/github.com/shipyard/shipyard

ENV GO15VENDOREXPERIMENT=1