FROM golang:1.7.4-alpine

ENV DOCKER_VERSION 1.13.0
ENV TAG latest
ENV PATH $PATH:/go/bin:/usr/local/go/bin

RUN apk -v add --update ca-certificates curl make git
RUN go get github.com/tools/godep

RUN curl -L https://get.docker.com/builds/Linux/x86_64/docker-${DOCKER_VERSION}.tgz | tar -zxO docker/docker > /usr/local/bin/docker && \
	chmod +x /usr/local/bin/docker

COPY . /go/src/github.com/shipyard/shipyard
WORKDIR /go/src/github.com/shipyard/shipyard
